### ISSUE TITLE
About RE3 Header info

### ISSUE THREAD

**Issue by KhaleedSA** [pmandin/reevengi-tools#3]
**I noticed you haven't add Header info yet,, i don't know if you forgot about them or you don't knows them,

but i have figured out how they work and what are they,, if you interested in them and you want to update your wiki,

here's  the link
https://www.tapatalk.com/groups/residentevil123/resident-evil-3-rdt-tutorial-t3233.html

it's better to download version 2,,, version 1 has some wrong info.**

**Comment by pmandin** [comment]
Hello,

Well, I did not know the whole header structure, so thanks for the info. I'll try to add it when I have some spare time.

**Comment by Grauen** [comment]
> **I noticed you haven't add Header info yet,, i don't know if you forgot about them or you don't knows them,
> 
> but i have figured out how they work and what are they,, if you interested in them and you want to update your wiki,
> 
> here's the link https://www.tapatalk.com/groups/residentevil123/resident-evil-3-rdt-tutorial-t3233.html
> 
> it's better to download version 2,,, version 1 has some wrong info.**
@KhaleedSA 
can you please re-upload the tutorial files?

**Comment by KhaleedSA** [comment]
> > **I noticed you haven't add Header info yet,, i don't know if you forgot about them or you don't knows them,
> > but i have figured out how they work and what are they,, if you interested in them and you want to update your wiki,
> > here's the link https://www.tapatalk.com/groups/residentevil123/resident-evil-3-rdt-tutorial-t3233.html
> > it's better to download version 2,,, version 1 has some wrong info.**
> > @KhaleedSA
> > can you please re-upload the tutorial files?

Hi @Grauen, Sure.
I made a new one on Google Document.
Any Update i do, it will be there.
https://docs.google.com/document/d/1S-dOt_oZeqKD9Na6QmjpL-7lmhSrFtfQdQa7pbbeK2A/edit?usp=sharing

**Comment by KhaleedSA** [comment]
Updating what @Grauen asked for.
