### ISSUE TITLE
bss2bmp: stderr (vlc: writing out of range: XXXXX)

### ISSUE THREAD

**Issue by Rus3545** [pmandin/reevengi-tools#4]
Hello.
Fix it please. [Examples](https://www.sendspace.com/file/rxn968).
I have compiled the 320x192 image version for SDL-1.2.15-win32. Or if I'm doing something wrong, tell me what exactly.
And if possible, add optional parameter setting the size of the pictures, they can differ in height and width.
Thanks.
P.S. Sorry for the translation difficulties.

**Comment by pmandin** [comment]
I added -w and -h parameters to set width and/or height.
